회원가입 API 이메일 중복여부 예외처리 필요
cocoding-ss/apjung-backend pull request #110
Opened 2020-12-05 21:49 UTC by YoungWukJeon

2020-12-05 21:55 UTC, YoungWukJeon commented
- 이메일을 통해 회원을 찾는 부분에서 index를 탈 것임을 확인했습니다.

![image](https://user-images.githubusercontent.com/20215884/101266170-cfbc3080-378f-11eb-8ca8-19efafb58002.png)

2020-12-05 21:57 UTC, YoungWukJeon commented
회원 가입 중에 이메일 중복으로 인해 회원 가입이 실패할 경우 기존 파라미터로 인한 400(BAD_REQUEST)와 다르게 코드는 400이지만 별도의 응답을 하도록 했습니다. RestDocs에는 아래와 같이 기존 성공 응답 아래에 실패 응답을 넣었습니다.

![image](https://user-images.githubusercontent.com/20215884/101266227-448f6a80-3790-11eb-82ce-28ded8c3f512.png)

2020-12-05 22:02 UTC, YoungWukJeon commented
@labyu 
Jenkins Job이 실패해서 보니까 SonarQube 계정 쪽이 문제인 것 같은데, 혹시 아이디/비밀번호가 변경되었나요? (실제 SonarQube 쪽에도 로그인이 되지 않습니다.)

2020-12-06 08:21 UTC, labyu commented
쿠버네티스 클러스터 리스타트에 의해 PV가 제대로 마운트되지 않아 소나큐브 테스트에 실패했습니다. 다시 테스트를 위해 이슈를 재시작합니다.

2020-12-06 08:34 UTC, labyu requested changes
BaseExceptionHandler

이부분 CustomMessageSourceResolver 클래스와 행동이 겹치는 것 같습니다. 혹시 예외메시지만 따로 가져오는 클래스를 작성하신 이유가 있을까요?

2020-12-06 08:35 UTC, YoungWukJeon commented
> 쿠버네티스 클러스터 재시작에 의해 PV가 제대로 마운트되지 않아 소나큐브 테스트에 실패했습니다. 다시 테스트를 위해 이슈를 재시작합니다.

확인했습니다

2020-12-06 08:42 UTC, YoungWukJeon commented
> BaseExceptionHandler
> 
> 이부분 CustomMessageSourceResolver 클래스와 행동이 겹치는 것 같습니다. 혹시 예외메시지만 따로 가져오는 클래스를 작성하신 이유가 있을까요?

CustomMessageSourceResolver를 통해서 400 valid 메시지나 template message(이메일 문구 등)를 처리하신 것 같은데 말씀하신것처럼 기능은 유사해 보일수 있지만 같은 400(BAD_REQUEST)이지만 서비스 레이어를 거치냐에 따라 exception 핸들링의 형태가 다르다고 생각해서 분리했습니다.

2020-12-06 09:07 UTC, labyu commented
> CustomMessageSourceResolver를 통해서 400 valid 메시지나 template message(이메일 문구 등)를 처리하신 것 같은데 말씀하신처럼 기능은 유사해 보일수 있지만 같은 400(BAD_REQUEST)이지만 서비스 레이어를 거치냐에 따라 exception 핸들링의 형태가 다르다고 생각해서 분리했습니다.

해당 클래스 메소드들의 return이 String인데, 이것은 결국 MessageSource를 resolve하는 것과 역할이 크게 다르지 않은 것 같습니다. 또한 현재 messageSource Bean을 사용하고 계신데, businessMessageSource와 validationMessageSource처럼 분리하시지 않은 이유가 궁금합니다. messageSource 빈은 해당 세개의 메시지 모두를 가져오는 빈입니다.

만약 BaseExceptionHandler를 통해 익셉션핸들링을 하고싶으시다면 아래같은 느낌이 더 낫지 않을까 싶습니다.

```java
@Component
public class CustomMessageSourceResolver {
    private final MessageSource validationMessageSource;
    private final MessageSource businessMessageSource;
    private final MessageSource exceptionMessageSource;

    protected static final String MESSAGE_KEY_PREFIX = "api.exception.";

    // 생성자 생략

    public String getExceptionMessage(RuntimeException exception) {
        return exceptionMessageSource.getMessage(code, null, LocaleContextHolder.getLocale());
    }

    private String findCodeByRuntimeExceptionType(RuntimeException exception) {
        if (exception instanceof DuplicatedEmailException) {
            return MESSAGE_KEY_PREFIX + "DuplicatedEmailException.message";
        }
        return MESSAGE_KEY_PREFIX + "UndefinedException.message";
    }
}
```

```java
@RequiredArgsConstructor
@RestControllerAdvice
public abstract class BaseExceptionHandler {
    protected final CustomMessageSourceResolver customMessageSourceResolver;
```

```java
@RestControllerAdvice
public class AuthExceptionHandler extends BaseExceptionHandler {
    public AuthExceptionHandler(MessageSource messageSource) {
        super(messageSource);
    }

    @ResponseStatus(HttpStatus.BAD_REQUEST)
    @ExceptionHandler(DuplicatedEmailException.class)
    public ErrorResponse duplicatedEmailException(DuplicatedEmailException exception) {
        final var message = Optional.ofNullable(exception.getMessage())
                .orElse(customMessageSourceResolver.getExceptionMessage(exception));
        return new ErrorResponse(message);
    }
}
```

2020-12-06 17:20 UTC, YoungWukJeon commented
> CustomMessageSourceResolver

리뷰 내용 반영했습니다!!

2020-12-07 07:58 UTC, labyu approved these changes

2020-12-07 07:58 UTC, labyu commented
Approve 했습니다 ㅎ.ㅎ

2020-12-07 12:01 UTC, merged