쇼핑몰 검색 및 리스팅 기능 개선
cocoding-ss/apjung-backend pull request #129
Opened 2020-12-26 21:55 UTC by YoungWukJeon

2020-12-28 06:01 UTC, labyu requested changes
ShopRepositoryImpl 부분의 검색쿼리 부분을 아래와 같이 변경해보고 테스트도 완료했습니다. 쇼핑몰 검색은 FROM을 QShop.shop에서 시작하는 것이 이해하는데 더 편할 것 같습니다. 

```java
@Override
    public List<Shop> findAllDynamicQueryOrderByName(String name, int pageNum, int pageSize) {
        return from(QShop.shop)
                .select(QShop.shop)
                .leftJoin(QShopTag.shopTag).on(QShop.shop.eq(QShopTag.shopTag.shop))
                .leftJoin(QTag.tag).on(QShopTag.shopTag.tag.eq(QTag.tag))
                .where(deleteCondition())
                .where(searchCondition(name))
                .where(safeLevelCondition())
                .groupBy(QShop.shop.id)
                .orderBy(QShop.shop.name.asc())
                .limit(pageSize)
                .offset(pageNum)
                .fetch();
    }

    @Override
    public List<Shop> findAllDynamicQueryOrderByCreatedAtDesc(String name, int pageNum, int pageSize) {
        return from(QShop.shop)
                .select(QShop.shop)
                    .leftJoin(QShopTag.shopTag).on(QShop.shop.eq(QShopTag.shopTag.shop))
                    .leftJoin(QTag.tag).on(QShopTag.shopTag.tag.eq(QTag.tag))
                .where(deleteCondition())
                .where(searchCondition(name))
                .where(safeLevelCondition())
                .groupBy(QShop.shop.id)
                .orderBy(QShop.shop.createdAt.desc())
                .limit(pageSize)
                .offset(pageNum)
                .fetch();
    }
```

2020-12-28 07:15 UTC, YoungWukJeon commented
두번째 leftJoin에 대해서는 tag가 null이면 shop_tag가 없다고 생각할수 있을까요?(soft delete에 걸렸다거나?)
그렇다고 한다면 innerJoin을 써도 괜찮을까요?

2020-12-28 07:18 UTC, labyu commented
innerJoin을 쓸 경우 태그가 없는 쇼핑몰은 검색결과에 포함되나용?

2020-12-28 07:23 UTC, YoungWukJeon commented
> innerJoin을 쓸 경우 태그가 없는 쇼핑몰은 검색결과에 포함되나용?

변경전 코드에서는 innerJoin을 했던것 같은데 한번 실행해보고 다시 알려드리겠습니다!

2020-12-28 14:41 UTC, YoungWukJeon reviewed
반영했습니다!

2020-12-29 00:18 UTC, labyu approved these changes

2020-12-29 01:16 UTC, merged